### ISSUE TITLE
Release TODO List

### ISSUE THREAD

**Issue by Levi-Armstrong** [marip8/plugin_loader#11]
List of things to finalize before releasing the package and updating things like Tesseract, etc. @marip8 Add anything I missed.

- [ ] Rename package, possibly to boost_plugin_loader
- [ ] Windows CI
- [ ] Support @johnwason python loading
- [ ] Port over a few function from the Tesseract version
- [ ] Add code coverage
